version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/cd
hooks:
  ApplicationStop:
    - location: scripts/stop_node_application.sh
  ApplicationStart:
    - location: scripts/start_node_application.sh